In [55]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [56]:
# Import and read the Health Rankings data
Start_df = pd.read_csv("Data/All_Data.csv")
Start_df.head()

,FIPS,Num_Per_100k,State,County,Percent_Smokers,Percent_Obese,Food_Environment_Index,Percent_Access_Exercise,Primary_Care_Physician_Rate,Mental_Health_Providers_Rate,Percent_Some_College,Percent_Unemployed,Income_Inequality_Ratio,Violent_Crime_Rate,Average_Daily_Air_Polution_Particle_Matter,Percent_Long_Commute_Drives_Alone,Percent_Rural
0,1001,107.0,Alabama,Autauga,19.0,36.0,7.1,71.0,45.0,13.0,61.9,5.3,4.4,266.0,10.8,41.0,42.0
1,1003,82.5,Alabama,Baldwin,17.0,29.0,7.9,69.0,73.0,89.0,63.8,5.4,4.6,217.0,9.6,40.0,42.3
2,1005,96.1,Alabama,Barbour,22.0,44.0,5.5,53.0,42.0,8.0,39.7,8.6,5.9,329.0,10.1,35.0,67.8
3,1007,112.3,Alabama,Bibb,20.0,38.0,7.6,49.0,53.0,9.0,49.8,6.6,4.2,147.0,10.5,49.0,68.4
4,1009,96.1,Alabama,Blount,20.0,36.0,8.5,32.0,21.0,9.0,53.9,5.5,4.1,212.0,11.3,60.0,90.0

In [57]:
Alabama_df=Start_df.groupby(["State"])

Alabama_df.head()

,FIPS,Num_Per_100k,State,County,Percent_Smokers,Percent_Obese,Food_Environment_Index,Percent_Access_Exercise,Primary_Care_Physician_Rate,Mental_Health_Providers_Rate,Percent_Some_College,Percent_Unemployed,Income_Inequality_Ratio,Violent_Crime_Rate,Average_Daily_Air_Polution_Particle_Matter,Percent_Long_Commute_Drives_Alone,Percent_Rural
0,1001,107.0,Alabama,Autauga,19.0,36.0,7.1,71.0,45.0,13.0,61.9,5.3,4.4,266.0,10.8,41.0,42.0
1,1003,82.5,Alabama,Baldwin,17.0,29.0,7.9,69.0,73.0,89.0,63.8,5.4,4.6,217.0,9.6,40.0,42.3
2,1005,96.1,Alabama,Barbour,22.0,44.0,5.5,53.0,42.0,8.0,39.7,8.6,5.9,329.0,10.1,35.0,67.8
3,1007,112.3,Alabama,Bibb,20.0,38.0,7.6,49.0,53.0,9.0,49.8,6.6,4.2,147.0,10.5,49.0,68.4
4,1009,96.1,Alabama,Blount,20.0,36.0,8.5,32.0,21.0,9.0,53.9,5.5,4.1,212.0,11.3,60.0,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119,56001,65.7,Wyoming,Albany,16.0,23.0,6.3,85.0,76.0,473.0,85.1,3.2,5.9,129.0,5.8,8.0,11.9
3120,56003,69.9,Wyoming,Big Horn,16.0,30.0,8.1,70.0,17.0,167.0,65.9,4.9,4.4,141.0,6.4,17.0,100.0
3121,56005,34.9,Wyoming,Campbell,17.0,34.0,8.5,49.0,39.0,176.0,60.1,7.1,3.7,152.0,7.9,15.0,29.1
3122,56007,60.3,Wyoming,Carbon,16.0,28.0,7.3,72.0,32.0,224.0,58.0,4.6,4.4,276.0,5.7,21.0,41.6
3123,56009,67.5,Wyoming,Converse,17.0,30.0,8.5,84.0,56.0,190.0,61.2,6.2,3.8,233.0,6.7,24.0,55.4

In [58]:
Smoker_df=Start_df['Percent_Smokers']
Smoker_df.head()

0    19.0
1    17.0
2    22.0
3    20.0
4    20.0
Name: Percent_Smokers, dtype: float64

In [59]:
State_df=Start_df.groupby(["State"])

State_df.head()

,FIPS,Num_Per_100k,State,County,Percent_Smokers,Percent_Obese,Food_Environment_Index,Percent_Access_Exercise,Primary_Care_Physician_Rate,Mental_Health_Providers_Rate,Percent_Some_College,Percent_Unemployed,Income_Inequality_Ratio,Violent_Crime_Rate,Average_Daily_Air_Polution_Particle_Matter,Percent_Long_Commute_Drives_Alone,Percent_Rural
0,1001,107.0,Alabama,Autauga,19.0,36.0,7.1,71.0,45.0,13.0,61.9,5.3,4.4,266.0,10.8,41.0,42.0
1,1003,82.5,Alabama,Baldwin,17.0,29.0,7.9,69.0,73.0,89.0,63.8,5.4,4.6,217.0,9.6,40.0,42.3
2,1005,96.1,Alabama,Barbour,22.0,44.0,5.5,53.0,42.0,8.0,39.7,8.6,5.9,329.0,10.1,35.0,67.8
3,1007,112.3,Alabama,Bibb,20.0,38.0,7.6,49.0,53.0,9.0,49.8,6.6,4.2,147.0,10.5,49.0,68.4
4,1009,96.1,Alabama,Blount,20.0,36.0,8.5,32.0,21.0,9.0,53.9,5.5,4.1,212.0,11.3,60.0,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3119,56001,65.7,Wyoming,Albany,16.0,23.0,6.3,85.0,76.0,473.0,85.1,3.2,5.9,129.0,5.8,8.0,11.9
3120,56003,69.9,Wyoming,Big Horn,16.0,30.0,8.1,70.0,17.0,167.0,65.9,4.9,4.4,141.0,6.4,17.0,100.0
3121,56005,34.9,Wyoming,Campbell,17.0,34.0,8.5,49.0,39.0,176.0,60.1,7.1,3.7,152.0,7.9,15.0,29.1
3122,56007,60.3,Wyoming,Carbon,16.0,28.0,7.3,72.0,32.0,224.0,58.0,4.6,4.4,276.0,5.7,21.0,41.6
3123,56009,67.5,Wyoming,Converse,17.0,30.0,8.5,84.0,56.0,190.0,61.2,6.2,3.8,233.0,6.7,24.0,55.4

In [60]:
average_smokers = State_df["Percent_Smokers"].mean()
average_smokers

State
Alabama                 20.641791
Alaska                  22.517241
Arizona                 16.666667
Arkansas                20.880000
California              12.517241
Colorado                14.968750
Connecticut             12.625000
Delaware                17.666667
District of Columbia    17.000000
Florida                 17.925373
Georgia                 19.849057
Hawaii                  13.000000
Idaho                   15.159091
Illinois                16.362745
Indiana                 19.739130
Iowa                    15.030303
Kansas                  16.104762
Kentucky                22.616667
Louisiana               21.109375
Maine                   17.500000
Maryland                14.958333
Massachusetts           14.642857
Michigan                18.602410
Minnesota               15.022989
Mississippi             20.695122
Missouri                21.695652
Montana                 17.267857
Nebraska                15.849462
Nevada                  17.588235
New Hampshire           15.300000
New Jersey              14.619048
New Mexico              16.303030
New York                17.725806
North Carolina          18.720000
North Dakota            17.207547
Ohio                    20.295455
Oklahoma                18.558442
Oregon                  15.916667
Pennsylvania            16.164179
Rhode Island            14.600000
South Carolina          18.608696
South Dakota            17.424242
Tennessee               22.168421
Texas                   15.622047
Utah                     9.758621
Vermont                 15.714286
Virginia                16.917293
Washington              14.666667
West Virginia           22.454545
Wisconsin               16.013889
Wyoming                 16.130435
Name: Percent_Smokers, dtype: float64

In [61]:
State_df.count()

,FIPS,Num_Per_100k,County,Percent_Smokers,Percent_Obese,Food_Environment_Index,Percent_Access_Exercise,Primary_Care_Physician_Rate,Mental_Health_Providers_Rate,Percent_Some_College,Percent_Unemployed,Income_Inequality_Ratio,Violent_Crime_Rate,Average_Daily_Air_Polution_Particle_Matter,Percent_Long_Commute_Drives_Alone,Percent_Rural
State,,,,,,,,,,,,,,,,
Alabama,67,67,67,67,67,67,67,65,65,67,67,67,66,67,67,67
Alaska,29,26,29,29,29,29,23,26,28,29,29,29,9,0,29,23
Arizona,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15
Arkansas,75,75,75,75,75,75,75,74,69,75,75,75,73,75,75,75
California,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58
Colorado,64,64,64,64,64,64,64,62,59,64,64,64,63,64,64,64
Connecticut,8,8,8,8,8,8,8,8,8,8,8,8,6,8,8,8
Delaware,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
District of Columbia,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Florida,67,67,67,67,67,67,67,65,65,67,67,67,67,67,67,67
Georgia,159,159,159,159,159,158,159,146,136,159,159,159,154,159,159,159
Hawaii,5,5,5,5,5,5,5,5,5,5,4,4,4,0,5,5
Idaho,44,44,44,44,44,44,44,43,42,44,44,44,44,44,44,44
Illinois,102,102,102,102,102,101,102,95,92,102,102,102,100,102,102,102
Indiana,92,92,92,92,92,90,92,89,90,92,92,92,69,92,92,92
Iowa,99,99,99,99,99,99,99,99,88,99,99,99,94,99,99,99
Kansas,105,105,105,105,105,105,105,100,80,105,105,105,101,105,105,105
Kentucky,120,120,120,120,120,117,120,115,115,120,120,120,118,120,120,120
Louisiana,64,64,64,64,64,64,64,62,63,64,64,64,63,64,64,64
Maine,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
Maryland,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
Massachusetts,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
Michigan,83,83,83,83,83,82,83,82,82,83,83,83,81,83,83,83
Minnesota,87,87,87,87,87,87,87,82,79,87,87,87,87,87,87,87
Mississippi,82,82,82,82,82,81,82,80,74,82,82,82,41,82,82,82
Missouri,115,115,115,115,115,115,115,110,109,115,115,115,114,115,115,115
Montana,56,56,56,56,56,56,56,54,48,56,56,56,52,56,56,56
Nebraska,93,90,93,93,93,93,93,87,76,93,93,93,66,93,93,93
Nevada,17,17,17,17,17,17,17,15,16,17,17,16,17,17,17,17
New Hampshire,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
New Jersey,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21
New Mexico,33,33,33,33,33,33,33,31,33,33,33,33,32,33,33,33
New York,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62
North Carolina,100,100,100,100,100,98,100,98,99,100,100,100,95,100,100,100
North Dakota,53,52,53,53,53,53,53,42,31,53,53,53,52,53,53,53
Ohio,88,88,88,88,88,88,88,88,88,88,88,88,86,88,88,88
Oklahoma,77,77,77,77,77,77,77,74,70,77,77,77,77,77,77,77
Oregon,36,36,36,36,36,36,36,36,35,36,36,36,35,36,36,36
Pennsylvania,67,67,67,67,67,67,67,66,66,67,67,67,67,67,67,67
Rhode Island,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
South Carolina,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46
South Dakota,66,66,66,66,66,66,66,56,39,66,66,66,54,66,66,65
Tennessee,95,95,95,95,95,94,95,91,87,95,95,95,95,95,95,95
Texas,254,254,254,254,254,253,254,234,208,254,254,254,253,254,254,254
Utah,29,29,29,29,29,29,29,28,28,29,29,29,28,29,29,29
Vermont,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
Virginia,133,133,133,133,133,128,133,126,129,133,133,133,133,133,133,133
Washington,39,39,39,39,39,39,39,37,39,39,39,39,39,39,39,39
West Virginia,55,55,55,55,55,55,55,54,55,55,55,55,48,55,55,55
Wisconsin,72,72,72,72,72,71,72,71,70,72,72,72,72,72,72,72
Wyoming,23,23,23,23,23,23,23,23,23,23,23,23,22,23,23,23

In [62]:
for col in Start_df.columns:
    print(col)

FIPS
Num_Per_100k
State
County
Percent_Smokers
Percent_Obese
Food_Environment_Index
Percent_Access_Exercise
Primary_Care_Physician_Rate
Mental_Health_Providers_Rate
Percent_Some_College
Percent_Unemployed
Income_Inequality_Ratio
Violent_Crime_Rate
Average_Daily_Air_Polution_Particle_Matter
Percent_Long_Commute_Drives_Alone
Percent_Rural

In [63]:
Average_Daily_Air_Polution_Particle_Matter_State = State_df["Average_Daily_Air_Polution_Particle_Matter"].mean()
Average_Daily_Air_Polution_Particle_Matter_State

State
Alabama                 10.328358
Alaska                        NaN
Arizona                  6.693333
Arkansas                10.049333
California               8.637931
Colorado                 5.826562
Connecticut              8.225000
Delaware                 9.400000
District of Columbia    10.900000
Florida                  7.452239
Georgia                  9.928302
Hawaii                        NaN
Idaho                    7.211364
Illinois                10.614706
Indiana                 11.080435
Iowa                     9.648485
Kansas                   8.391429
Kentucky                 9.989167
Louisiana                9.560937
Maine                    7.475000
Maryland                 9.770833
Massachusetts            8.457143
Michigan                 8.875904
Minnesota                9.302299
Mississippi              9.489024
Missouri                 9.687826
Montana                  6.283929
Nebraska                 8.040860
Nevada                   5.817647
New Hampshire            7.920000
New Jersey               9.585714
New Mexico               6.684848
New York                 8.706452
North Carolina           9.008000
North Dakota             7.441509
Ohio                    11.378409
Oklahoma                 8.988312
Oregon                   7.016667
Pennsylvania            10.373134
Rhode Island             7.760000
South Carolina           9.706522
South Dakota             7.619697
Tennessee                9.751579
Texas                    8.209843
Utah                     6.396552
Vermont                  7.550000
Virginia                 8.790226
Washington               6.992308
West Virginia            9.523636
Wisconsin                9.148611
Wyoming                  6.573913
Name: Average_Daily_Air_Polution_Particle_Matter, dtype: float64

In [64]:
Food_Environment_Index_State = State_df["Food_Environment_Index"].mean()
Food_Environment_Index_State

State
Alabama                 6.726866
Alaska                  6.134483
Arizona                 6.073333
Arkansas                6.277333
California              7.703448
Colorado                7.814063
Connecticut             8.287500
Delaware                8.233333
District of Columbia    8.400000
Florida                 6.958209
Georgia                 6.975316
Hawaii                  7.560000
Idaho                   7.215909
Illinois                7.996040
Indiana                 7.978889
Iowa                    8.189899
Kansas                  7.525714
Kentucky                7.470085
Louisiana               6.728125
Maine                   7.775000
Maryland                8.358333
Massachusetts           8.492857
Michigan                7.818293
Minnesota               8.381609
Mississippi             5.767901
Missouri                7.216522
Montana                 6.941071
Nebraska                7.446237
Nevada                  7.041176
New Hampshire           8.560000
New Jersey              8.471429
New Mexico              6.212121
New York                8.253226
North Carolina          7.202041
North Dakota            8.422642
Ohio                    7.660227
Oklahoma                6.945455
Oregon                  7.191667
Pennsylvania            8.146269
Rhode Island            8.040000
South Carolina          6.923913
South Dakota            6.745455
Tennessee               7.527660
Texas                   6.968379
Utah                    7.082759
Vermont                 8.228571
Virginia                7.945312
Washington              7.443590
West Virginia           7.490909
Wisconsin               8.314085
Wyoming                 7.908696
Name: Food_Environment_Index, dtype: float64

In [65]:
Percent_Unemployed_State = State_df["Percent_Unemployed"].mean()
Percent_Unemployed_State

State
Alabama                 6.831343
Alaska                  9.103448
Arizona                 7.586667
Arkansas                4.665333
California              6.874138
Colorado                3.406250
Connecticut             4.937500
Delaware                4.466667
District of Columbia    6.000000
Florida                 5.138806
Georgia                 6.083648
Hawaii                  3.275000
Idaho                   4.397727
Illinois                6.084314
Indiana                 4.479348
Iowa                    3.675758
Kansas                  4.057143
Kentucky                6.279167
Louisiana               7.014062
Maine                   4.343750
Maryland                4.820833
Massachusetts           3.978571
Michigan                5.842169
Minnesota               4.652874
Mississippi             6.900000
Missouri                5.057391
Montana                 4.367857
Nebraska                3.140860
Nevada                  5.664706
New Hampshire           2.820000
New Jersey              5.314286
New Mexico              7.193939
New York                5.088710
North Carolina          5.641000
North Dakota            3.586792
Ohio                    5.420455
Oklahoma                5.384416
Oregon                  5.594444
Pennsylvania            5.970149
Rhode Island            4.920000
South Carolina          5.678261
South Dakota            3.266667
Tennessee               5.666316
Texas                   5.186614
Utah                    4.803448
Vermont                 3.750000
Virginia                4.666165
Washington              6.828205
West Virginia           6.994545
Wisconsin               4.561111
Wyoming                 5.017391
Name: Percent_Unemployed, dtype: float64

In [66]:
Income_Inequality_Ratio_State = State_df["Income_Inequality_Ratio"].mean()
Income_Inequality_Ratio_State

State
Alabama                 5.241791
Alaska                  4.189655
Arizona                 4.706667
Arkansas                4.793333
California              4.832759
Colorado                4.290625
Connecticut             4.725000
Delaware                4.233333
District of Columbia    7.200000
Florida                 4.523881
Georgia                 4.987421
Hawaii                  4.475000
Idaho                   4.125000
Illinois                4.390196
Indiana                 3.991304
Iowa                    4.086869
Kansas                  4.037143
Kentucky                4.955000
Louisiana               5.504688
Maine                   4.418750
Maryland                4.316667
Massachusetts           5.028571
Michigan                4.213253
Minnesota               4.104598
Mississippi             5.248780
Missouri                4.314783
Montana                 4.344643
Nebraska                4.029032
Nevada                  4.168750
New Hampshire           4.220000
New Jersey              4.900000
New Mexico              4.963636
New York                4.672581
North Carolina          4.721000
North Dakota            4.526415
Ohio                    4.335227
Oklahoma                4.553247
Oregon                  4.347222
Pennsylvania            4.291045
Rhode Island            4.860000
South Carolina          4.941304
South Dakota            4.301515
Tennessee               4.578947
Texas                   4.712205
Utah                    3.896552
Vermont                 4.271429
Virginia                4.463158
Washington              4.441026
West Virginia           4.663636
Wisconsin               4.022222
Wyoming                 4.217391
Name: Income_Inequality_Ratio, dtype: float64

In [67]:
average_smokers_state=average_smokers
average_smokers_state

State
Alabama                 20.641791
Alaska                  22.517241
Arizona                 16.666667
Arkansas                20.880000
California              12.517241
Colorado                14.968750
Connecticut             12.625000
Delaware                17.666667
District of Columbia    17.000000
Florida                 17.925373
Georgia                 19.849057
Hawaii                  13.000000
Idaho                   15.159091
Illinois                16.362745
Indiana                 19.739130
Iowa                    15.030303
Kansas                  16.104762
Kentucky                22.616667
Louisiana               21.109375
Maine                   17.500000
Maryland                14.958333
Massachusetts           14.642857
Michigan                18.602410
Minnesota               15.022989
Mississippi             20.695122
Missouri                21.695652
Montana                 17.267857
Nebraska                15.849462
Nevada                  17.588235
New Hampshire           15.300000
New Jersey              14.619048
New Mexico              16.303030
New York                17.725806
North Carolina          18.720000
North Dakota            17.207547
Ohio                    20.295455
Oklahoma                18.558442
Oregon                  15.916667
Pennsylvania            16.164179
Rhode Island            14.600000
South Carolina          18.608696
South Dakota            17.424242
Tennessee               22.168421
Texas                   15.622047
Utah                     9.758621
Vermont                 15.714286
Virginia                16.917293
Washington              14.666667
West Virginia           22.454545
Wisconsin               16.013889
Wyoming                 16.130435
Name: Percent_Smokers, dtype: float64

In [68]:
average_smokers_state.describe()

count    51.000000
mean     17.197884
std       2.827913
min       9.758621
25%      15.229545
50%      16.917293
75%      18.664348
max      22.616667
Name: Percent_Smokers, dtype: float64

In [69]:
Income_Inequality_Ratio_State.describe()

count    51.000000
mean      4.556417
std       0.524223
min       3.896552
25%       4.226667
50%       4.441026
75%       4.759167
max       7.200000
Name: Income_Inequality_Ratio, dtype: float64

In [70]:
Percent_Unemployed_State.describe()

count    51.000000
mean      5.225064
std       1.289874
min       2.820000
25%       4.432197
50%       5.088710
75%       5.985075
max       9.103448
Name: Percent_Unemployed, dtype: float64

In [71]:
Average_Daily_Air_Polution_Particle_Matter_State.describe()

count    49.000000
mean      8.617632
std       1.433657
min       5.817647
25%       7.475000
50%       8.790226
75%       9.687826
max      11.378409
Name: Average_Daily_Air_Polution_Particle_Matter, dtype: float64

In [72]:
Food_Environment_Index_State = State_df["Food_Environment_Index"].mean()
Food_Environment_Index_State.describe()

count    51.000000
mean      7.513175
std       0.719281
min       5.767901
25%       6.971848
50%       7.527660
75%       8.168084
max       8.560000
Name: Food_Environment_Index, dtype: float64

In [77]:
%matplotlib

Using matplotlib backend: <object object at 0x7ff6cd17dde0>